Ek list lo [5, 10, 15, 20, 25]

NumPy array banao

Double karo values

Pandas Series me convert karo

In [144]:
import numpy as np
import pandas as pd

In [145]:
lst = np.array([5, 10, 15, 20, 25])
lst


array([ 5, 10, 15, 20, 25])

In [146]:
double_values = lst*2
double_values

array([10, 20, 30, 40, 50])

In [147]:
srs = pd.Series(double_values)
print(srs)

0    10
1    20
2    30
3    40
4    50
dtype: int64


CSV: people.csv (name, age)

Average age

Oldest person

Age > 25 waale log

In [148]:
people = pd.DataFrame({
    "Name": ['Shahnawaz', 'Abdullah', 'Abhay', 'Vyom', 'Yash', 'Ujjawal', 'Pranav', 'Laksh', 'Rishab'],
    "Age": [18, 19, 26, 21, 22, 27, 24, 25, 20]
})

people

,Name,Age
0,Shahnawaz,18
1,Abdullah,19
2,Abhay,26
3,Vyom,21
4,Yash,22
5,Ujjawal,27
6,Pranav,24
7,Laksh,25
8,Rishab,20


In [149]:
print(people['Age'].mean())


22.444444444444443


In [150]:
g_25 = people[people['Age']> 25]
print(g_25)

      Name  Age
2    Abhay   26
5  Ujjawal   27


In [151]:
people.loc[people['Age'].idxmax()]

Name    Ujjawal
Age          27
Name: 5, dtype: object

Ek DataFrame banao:

Product   Price
A         100
B         250
C         400


Price ka NumPy array

Mean price

Price > 200 products

In [152]:
df = pd.DataFrame({
    'Product' : ['Hell', 'RedBull', 'Monster', 'Campa', 'Coffee'],
    'Price': [100, 200, 300, 250, 400]
})
df

,Product,Price
0,Hell,100
1,RedBull,200
2,Monster,300
3,Campa,250
4,Coffee,400


In [153]:
price_array = np.array(df['Price'])
price_array

array([100, 200, 300, 250, 400])

In [154]:
print(df['Price'].mean())

250.0


In [155]:
df[df['Price']>200]

,Product,Price
2,Monster,300
3,Campa,250
4,Coffee,400


Random 8 numbers generate karo

DataFrame me daalo

Odd numbers filter karo

In [156]:
nums = np.random.randint(10, 100, 8)
print(nums)

[62 27 12 97 48 61 13 21]


In [157]:
df = pd.DataFrame(nums)
df

,0
0,62
1,27
2,12
3,97
4,48
5,61
6,13
7,21


In [158]:
odd_num = df[nums%2!=0]
odd_num

,0
1,27
3,97
5,61
6,13
7,21


CSV: marks.csv (name, marks)

Class average

Top 2 students

In [159]:
mark = pd.read_csv('marks.csv')
mark

,name,subject,marks
0,Aman,Maths,78
1,Aman,Physics,65
2,Riya,Maths,88
3,Riya,Physics,92
4,Shiv,Maths,30
5,Shiv,Physics,40


In [160]:
class_avg = mark['marks'].mean()
print(class_avg)

65.5


In [161]:
sort_marks = mark['marks'].sort_values(ascending=False)
sort_marks

3    92
2    88
0    78
1    65
5    40
4    30
Name: marks, dtype: int64

In [162]:
mark.sort_values(by='marks', ascending=False).head(2)

,name,subject,marks
3,Riya,Physics,92
2,Riya,Maths,88


sales.csv (date, product, amount)
Tasks:

Total sales

Product-wise total sales

Highest selling product

In [163]:
df = pd.read_csv('sales.csv')
df

,date,product,amount
0,2026-01-01,Mobile,20000
1,2026-01-01,Laptop,50000
2,2026-01-02,Mobile,15000
3,2026-01-02,Headphones,3000
4,2026-01-03,Laptop,40000
5,2026-01-03,Mobile,18000


In [164]:
total_sales = df['amount'].sum()
print("₹", total_sales)

₹ 146000


In [165]:
product_sales = df.groupby(by='product')['amount'].sum()
product_sales

product
Headphones     3000
Laptop        90000
Mobile        53000
Name: amount, dtype: int64

In [166]:
prdct_sale = pd.DataFrame(product_sales)
prdct_sale

,amount
product,
Headphones,3000
Laptop,90000
Mobile,53000


In [167]:
prdct_sale.loc[prdct_sale['amount'].idxmax()]

amount    90000
Name: Laptop, dtype: int64

Random 3x3 NumPy matrix banao

DataFrame me convert

Diagonal elements nikaalo

Matrix ka sum

In [168]:
Matrix_3x3 = np.random.randint(10, 100, (3,3))
Matrix_3x3

array([[85, 31, 38],
       [99, 71, 17],
       [13, 60, 70]])

In [169]:
df = pd.DataFrame(Matrix_3x3)
df

,0,1,2
0,85,31,38
1,99,71,17
2,13,60,70


In [170]:
np.diag(Matrix_3x3)

array([85, 71, 70])

In [171]:
print(np.sum(Matrix_3x3))

484


CSV: employees.csv (name, dept, salary)

Dept-wise max salary

Overall average salary

Salary < average waale log

In [172]:
emp = pd.read_csv('employees.csv')
emp

,name,department,salary
0,Aman,IT,60000
1,Riya,HR,45000
2,Shiv,IT,75000
3,Neha,Finance,52000
4,Arjun,HR,48000


In [173]:
max_salary = emp.groupby(by='department')['salary'].max()
max_salary

department
Finance    52000
HR         48000
IT         75000
Name: salary, dtype: int64

In [174]:
emp['salary'].mean()

np.float64(56000.0)

In [175]:
emp[emp['salary']< emp['salary'].mean()]

,name,department,salary
1,Riya,HR,45000
3,Neha,Finance,52000
4,Arjun,HR,48000


CSV: weather.csv (day, temp, humidity)

Max temp day

Avg humidity

Temp > 30 & humidity < 60 waale days

In [176]:
weather = pd.read_csv('weather.csv')
weather

,day,temperature,humidity
0,Mon,32,75
1,Tue,35,70
2,Wed,30,60
3,Thu,28,55
4,Fri,36,54
5,Sat,34,53
6,Sun,29,45


In [177]:
max_temp_day = weather.loc[weather['temperature'].idxmax()]
max_temp_day

day            Fri
temperature     36
humidity        54
Name: 4, dtype: object

In [178]:
print(weather['humidity'].mean())

58.857142857142854


In [180]:
weather[(weather['temperature']>30) & (weather['humidity']<60)]

,day,temperature,humidity
4,Fri,36,54
5,Sat,34,53
